name: file_sizes
description: Get the Human readable size of the file. It is purely written in dart and support both number and string as parameter and number.
version: 1.0.1
homepage: https://github.com/AnmolSethi/file_size.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.3"

dev_dependencies:
  flutter_test:
    sdk: flutter
