name: file_size
description: Human readable size of the file.
version: 1.0.0
homepage: https://github.com/AnmolSethi/file_size.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
