name: file_sizes
description: Get the Human readable size of the file. It is purely written in dart and support both number and string as parameters.
version: 1.0.4
homepage: https://github.com/AnmolSethi/file_size.git

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
